// <auto-generated />
using System;
using AirMastera.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AirMastera.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AirMasteraDbContext))]
    [Migration("20230717103722_UpdateRepairTable")]
    partial class UpdateRepairTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AirMastera.Infrastructure.Data.Models.CarDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PersonDbId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("PersonDbId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("AirMastera.Infrastructure.Data.Models.PersonDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("AirMastera.Infrastructure.Data.Models.RepairDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CarDbId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PartType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CarDbId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("AirMastera.Infrastructure.Data.Models.CarDb", b =>
                {
                    b.HasOne("AirMastera.Infrastructure.Data.Models.PersonDb", "PersonDb")
                        .WithMany("Cars")
                        .HasForeignKey("PersonDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonDb");
                });

            modelBuilder.Entity("AirMastera.Infrastructure.Data.Models.RepairDb", b =>
                {
                    b.HasOne("AirMastera.Infrastructure.Data.Models.CarDb", "CarDb")
                        .WithMany("Repairs")
                        .HasForeignKey("CarDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarDb");
                });

            modelBuilder.Entity("AirMastera.Infrastructure.Data.Models.CarDb", b =>
                {
                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("AirMastera.Infrastructure.Data.Models.PersonDb", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
