version: '3.1'

services:
    airmastera:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - '4321:4321'